name: Lighthouse.io

on:
  workflow_call:

jobs:
  lighthouse-tests:
    runs-on: ubuntu-latest
    name: Run Google Lighthouse tests
    steps:
      - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
        with:
          php-version: "8.1"
      - uses: actions/download-artifact@v2
        with:
          name: laravel
          path: ${{ github.workspace }}
      - name: Get Composer Cache Directory
        id: composer-cache
        run: |
          echo "::set-output name=dir::$(composer config cache-files-dir)"
      - uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-
      - name: Install composer dependencies
        run: composer install -q --no-ansi --no-interaction --no-progress --prefer-dist --ignore-platform-reqs --no-dev
      - name: Expose Laravel at http://localhost:8000
        run: php artisan serve --no-reload &
        env:
          APP_ENV: ci
          BASIC_AUTH: false
          DB_CONNECTION: sqlite
          DB_DATABASE: "${{ github.workspace }}/database/database.sqlite"
          DB_FOREIGN_KEYS: true
          APP_URL: http://localhost:8000
      - name: Get URLs
        id: getUrls
        run: echo "::set-output name=urls::$(cat ci/urls.txt | xargs | sed -e 's/ /,/g')"
      - name: Lighthouse
        uses: foo-software/lighthouse-check-action@master
        id: lighthouseCheck
        with:
          prCommentEnabled: true
          prCommentSaveOld: false
          gitHubAccessToken: ${{ secrets.GITHUB_TOKEN }}
          urls: ${{ steps.getUrls.outputs.urls }}
