name: Master PR workflow

on:
  pull_request:
    branches: [master]

env:
  APP_ENV: ci
  BASIC_AUTH: false
  DB_CONNECTION: sqlite
  DB_DATABASE: "${{ github.workspace }}/database/database.sqlite"
  DB_FOREIGN_KEYS: true
  APP_URL: http://localhost:8000

jobs:
  build-laravel:
    uses: ./.github/workflows/build-laravel.yml

  phpunit-tests:
    needs: build-laravel
    uses: ./.github/workflows/phpunit-tests.yml

  zap-scan:
    needs: phpunit-tests
    uses: ./.github/workflows/owasp-zap.yml

  # sitespeedio-scan:
  #   needs: build-laravel
  #   uses: ./.github/workflows/sitespeed.io.yml

  lighthouse-scan:
    needs: phpunit-tests
    uses: ./.github/workflows/lighthouse.yml

  # enlightn-scan:
  #   needs: build-laravel
  #   uses: ./.github/workflows/enlightn.yml

concurrency:
  group: pr-master-${{ github.ref }}-1
  cancel-in-progress: true
